export const products = [
    {
      id: 1143155,
      img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
      productName: "Acer Nitro 5",
      countCustomer: 2000,
      company: "Intel",
      madeIn: "Singapore",
      present: "John Doe",
      type: "Computer",
      date: "March",
      sell: 300,
      buy: 500,
      amount: 785,
      like: 5,
      remain: 200
    },
    {
      id: 2235235,
      img: "https://m.media-amazon.com/images/I/31JaiPXYI8L._AC_UY327_FMwebp_QL65_.jpg",
      productName: "Playstation 5",
      countCustomer: 1200,
      company: "Sona",
      madeIn: "Australia",
      present: "Prince Jane",
      type: "Game devices",
      date: "August",
      sell: 500,
      buy: 200,
      amount: 585,
      like: 3,
      remain: 400
      
    },
    {
      id: 2342353,
      productName: "Redragon S101",
      img: "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg",
      countCustomer: 5000,
      company: "SuperVin",
      madeIn: "Turkey",
      present: "Daniel Celzo",
      type: "TypeComputer",
      date: "September",
      sell: 100,
      buy: 20,
      amount: 85,
      like: 1,
      remain: 120
    
    },
    {
      id: 2357741,
      productName: "Razer Blade 15",
      img: "https://m.media-amazon.com/images/I/71wF7YDIQkL._AC_UY327_FMwebp_QL65_.jpg",
      countCustomer: 2600,
      company: "Malacia",
      madeIn: "Spain",
      present: "Eric Pham",
      type: "Laptop",
      date: "December",
      sell: 1200,
      buy: 1000,
      amount: 850,
      like: 5,
      remain: 20
    },
    {
      id: 2342355,
      productName: "ASUS ROG Strix",
      img: "https://m.media-amazon.com/images/I/81hH5vK-MCL._AC_UY327_FMwebp_QL65_.jpg",
      countCustomer: 3260,
      company: "Anaconda",
      madeIn: "Portugal",
      present: "Victoria Secret",
      type: "Advaced Laptop",
      date: "January",
      sell: 2200,
      buy: 1500,
      amount: 2850,
      like: 4,
      remain: 1000
        
    },
    {
      id: 2382313,
      productName: "Redragon S101",
      img: "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg",
      countCustomer: 400,
      company: "Applewatch",
      madeIn: "China",
      present: "Tina Vincent",
      type: "Mouse",
      date: "July",
      sell: 2000,
      buy: 300,
      amount: 805,
      like: 3,
      remain: 1200
    },
  ];